In [ ]:
import json
import pandas as pd

lat = []
lon = []
type = []
count_none = 0

json_file = open('input_data.json')
json_df = json.load(json_file)
 
# Iterating through the json
for visit in json_df['visits']:
  if visit is not None:
    if  list(visit.values())[0] == int(list(visit.values())[0]) and list(visit.values())[1] == str(list(visit.values())[1]) and list(visit.values())[2] == float(list(visit.values())[2]) and list(visit.values())[3] == float(list(visit.values())[3]):         
      lat.append(visit['lat'])
      lon.append(visit['lon'])
      type.append(visit['type'])
  else:
    count_none += 1

original_df = pd.DataFrame({'lon': lon, 'lat':lat, 'type': type})
Matrix = original_df[original_df.columns[0:2]]

In [2]:
import pandas as pd

df = pd.read_csv('RUTAS_FINAL.csv')
display(df)

    Unnamed: 0  Travel_Index  ...  Cluster_Final pickup_state
0            0             1  ...              0        False
1            1             2  ...              0        False
2            2             3  ...              0        False
3            3             4  ...              0        False
4            4             5  ...              0        False
..         ...           ...  ...            ...          ...
73          73            44  ...             10        False
74          74            45  ...             10        False
75          75            46  ...             10        False
76          76            47  ...             10        False
77          77            48  ...             10        False

[78 rows x 9 columns]

In [50]:
import json

api_calls = {}

api_calls['id']      = []
api_calls['status']  = []
api_calls['results'] = []

data = {}
data['global_cluster'] = []
data['visits'] = []

for cluster in df.Cluster_Final.unique():
  data['global_cluster'].append(int(cluster)) 

  for visit in df[df.Cluster_Final == cluster].index :
    data['visits'].append({
        'visit_id': int(df[df.Cluster_Final == cluster].visit_id[visit]),
        'Travel_Index': int(df[df.Cluster_Final == cluster].Travel_Index[visit])
                          })
    api_calls['results'].append(data)
    data['visits'] = []
    
api_calls['id'].append('123151')
api_calls['status'].append('completed')

with open('data.txt', 'w') as outfile:
  json.dump(api_calls, outfile)